name: 'secure_data_pipeline'
version: '1.0.0'
config-version: 2

profile: 'secure_data_pipeline'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  secure_data_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
