with source as (
    select * from {{ source('raw', 'RAW_ECOMMERCE_ORDERS') }}
)

select
    "order_id"::varchar as order_id,
    "order_date"::date as order_date,
    {{ yes_no_to_boolean('"is_weekend"') }} as is_weekend,
    "order_status"::varchar as order_status,
    "return_reason"::varchar as return_reason,
    "customer_id"::varchar as customer_id,
    "customer_name"::varchar as customer_name,
    "gender"::varchar as gender,
    "age"::number as age,
    "customer_segment"::varchar as customer_segment,
    "country"::varchar as country,
    "city"::varchar as city,
    "customer_loyalty_score"::float as customer_loyalty_score,
    "total_orders_by_customer"::number as total_orders_by_customer,
    "account_creation_date"::date as account_creation_date,
    "product_id"::varchar as product_id,
    "product_name"::varchar as product_name,
    "category"::varchar as category,
    "sub_category"::varchar as sub_category,
    "brand"::varchar as brand,
    "product_rating_avg"::float as product_rating_avg,
    "product_reviews_count"::number as product_reviews_count,
    "stock_quantity"::number as stock_quantity,
    "unit_price_usd"::float as unit_price_usd,
    "quantity"::number as quantity,
    "discount_percent"::float as discount_percent,
    "discount_amount_usd"::float as discount_amount_usd,
    "total_price_usd"::float as total_price_usd,
    "cost_usd"::float as cost_usd,
    "profit_usd"::float as profit_usd,
    "tax_usd"::float as tax_usd,
    "currency"::varchar as currency,
    "payment_method"::varchar as payment_method,
    "payment_status"::varchar as payment_status,
    {{ yes_no_to_boolean('"installment_plan"') }} as installment_plan,
    "shipping_method"::varchar as shipping_method,
    "shipping_cost_usd"::float as shipping_cost_usd,
    "delivery_days"::number as delivery_days,
    "shipping_country"::varchar as shipping_country,
    "warehouse_location"::varchar as warehouse_location,
    "delivery_status"::varchar as delivery_status,
    "rating"::number as rating,
    "review_sentiment"::varchar as review_sentiment,
    "customer_feedback"::varchar as customer_feedback,
    {{ yes_no_to_boolean('"coupon_used"') }} as coupon_used,
    "coupon_code"::varchar as coupon_code,
    "campaign_source"::varchar as campaign_source,
    "device_type"::varchar as device_type,
    "traffic_source"::varchar as traffic_source,
    "session_duration_minutes"::float as session_duration_minutes,
    "pages_visited"::number as pages_visited,
    {{ yes_no_to_boolean('"abandoned_cart_before"') }} as abandoned_cart_before,
    "fraud_risk_score"::float as fraud_risk_score,
    "profit_margin_percent"::float as profit_margin_percent,
    "order_priority"::varchar as order_priority,
    {{ yes_no_to_boolean('"support_ticket_created"') }} as support_ticket_created,
    "SOURCE_FILE"::varchar as source_file,
    "LOADED_AT"::timestamp_ltz as loaded_at
from source
